<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command_loader' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/CommandLoader/CommandLoaderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/console/CommandLoader/ContainerCommandLoader.php';

return $this->services['console.command_loader'] = new \Symfony\Component\Console\CommandLoader\ContainerCommandLoader(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'console.command.about' => ['privates', 'console.command.about', 'getConsole_Command_AboutService.php', true],
    'console.command.assets_install' => ['privates', 'console.command.assets_install', 'getConsole_Command_AssetsInstallService.php', true],
    'console.command.cache_clear' => ['privates', 'console.command.cache_clear', 'getConsole_Command_CacheClearService.php', true],
    'console.command.cache_pool_clear' => ['privates', 'console.command.cache_pool_clear', 'getConsole_Command_CachePoolClearService.php', true],
    'console.command.cache_pool_delete' => ['privates', 'console.command.cache_pool_delete', 'getConsole_Command_CachePoolDeleteService.php', true],
    'console.command.cache_pool_prune' => ['privates', 'console.command.cache_pool_prune', 'getConsole_Command_CachePoolPruneService.php', true],
    'console.command.cache_warmup' => ['privates', 'console.command.cache_warmup', 'getConsole_Command_CacheWarmupService.php', true],
    'console.command.config_debug' => ['privates', 'console.command.config_debug', 'getConsole_Command_ConfigDebugService.php', true],
    'console.command.config_dump_reference' => ['privates', 'console.command.config_dump_reference', 'getConsole_Command_ConfigDumpReferenceService.php', true],
    'console.command.container_debug' => ['privates', 'console.command.container_debug', 'getConsole_Command_ContainerDebugService.php', true],
    'console.command.debug_autowiring' => ['privates', 'console.command.debug_autowiring', 'getConsole_Command_DebugAutowiringService.php', true],
    'console.command.event_dispatcher_debug' => ['privates', 'console.command.event_dispatcher_debug', 'getConsole_Command_EventDispatcherDebugService.php', true],
    'console.command.router_debug' => ['privates', 'console.command.router_debug', 'getConsole_Command_RouterDebugService.php', true],
    'console.command.router_match' => ['privates', 'console.command.router_match', 'getConsole_Command_RouterMatchService.php', true],
    'console.command.yaml_lint' => ['privates', 'console.command.yaml_lint', 'getConsole_Command_YamlLintService.php', true],
    'old_sound_rabbit_mq.anon_consumer_command' => ['privates', 'old_sound_rabbit_mq.anon_consumer_command', 'getOldSoundRabbitMq_AnonConsumerCommandService.php', true],
    'old_sound_rabbit_mq.batch_consumer_command' => ['privates', 'old_sound_rabbit_mq.batch_consumer_command', 'getOldSoundRabbitMq_BatchConsumerCommandService.php', true],
    'old_sound_rabbit_mq.command.rpc_server_command' => ['privates', 'old_sound_rabbit_mq.command.rpc_server_command', 'getOldSoundRabbitMq_Command_RpcServerCommandService.php', true],
    'old_sound_rabbit_mq.command.setup_fabric_command' => ['privates', 'old_sound_rabbit_mq.command.setup_fabric_command', 'getOldSoundRabbitMq_Command_SetupFabricCommandService.php', true],
    'old_sound_rabbit_mq.command.std_in_producer_command' => ['privates', 'old_sound_rabbit_mq.command.std_in_producer_command', 'getOldSoundRabbitMq_Command_StdInProducerCommandService.php', true],
    'old_sound_rabbit_mq.consumer_command' => ['privates', 'old_sound_rabbit_mq.consumer_command', 'getOldSoundRabbitMq_ConsumerCommandService.php', true],
    'old_sound_rabbit_mq.delete_command' => ['privates', 'old_sound_rabbit_mq.delete_command', 'getOldSoundRabbitMq_DeleteCommandService.php', true],
    'old_sound_rabbit_mq.dynamic_consumer_command' => ['privates', 'old_sound_rabbit_mq.dynamic_consumer_command', 'getOldSoundRabbitMq_DynamicConsumerCommandService.php', true],
    'old_sound_rabbit_mq.multiple_consumer_command' => ['privates', 'old_sound_rabbit_mq.multiple_consumer_command', 'getOldSoundRabbitMq_MultipleConsumerCommandService.php', true],
    'old_sound_rabbit_mq.purge_consumer_command' => ['privates', 'old_sound_rabbit_mq.purge_consumer_command', 'getOldSoundRabbitMq_PurgeConsumerCommandService.php', true],
]), ['about' => 'console.command.about', 'assets:install' => 'console.command.assets_install', 'cache:clear' => 'console.command.cache_clear', 'cache:pool:clear' => 'console.command.cache_pool_clear', 'cache:pool:prune' => 'console.command.cache_pool_prune', 'cache:pool:delete' => 'console.command.cache_pool_delete', 'cache:warmup' => 'console.command.cache_warmup', 'debug:config' => 'console.command.config_debug', 'config:dump-reference' => 'console.command.config_dump_reference', 'debug:container' => 'console.command.container_debug', 'debug:autowiring' => 'console.command.debug_autowiring', 'debug:event-dispatcher' => 'console.command.event_dispatcher_debug', 'debug:router' => 'console.command.router_debug', 'router:match' => 'console.command.router_match', 'lint:yaml' => 'console.command.yaml_lint', 'rabbitmq:anon-consumer' => 'old_sound_rabbit_mq.anon_consumer_command', 'rabbitmq:batch:consumer' => 'old_sound_rabbit_mq.batch_consumer_command', 'rabbitmq:consumer' => 'old_sound_rabbit_mq.consumer_command', 'rabbitmq:delete' => 'old_sound_rabbit_mq.delete_command', 'rabbitmq:dynamic-consumer' => 'old_sound_rabbit_mq.dynamic_consumer_command', 'rabbitmq:multiple-consumer' => 'old_sound_rabbit_mq.multiple_consumer_command', 'rabbitmq:purge' => 'old_sound_rabbit_mq.purge_consumer_command', 'rabbitmq:rpc-server' => 'old_sound_rabbit_mq.command.rpc_server_command', 'rabbitmq:setup-fabric' => 'old_sound_rabbit_mq.command.setup_fabric_command', 'rabbitmq:stdin-producer' => 'old_sound_rabbit_mq.command.std_in_producer_command']);
