<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.access.decision_manager' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-core/Authorization/AccessDecisionManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-core/Authorization/TraceableAccessDecisionManager.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-core/Authorization/AccessDecisionManager.php';

return $this->privates['debug.security.access.decision_manager'] = new \Symfony\Component\Security\Core\Authorization\TraceableAccessDecisionManager(new \Symfony\Component\Security\Core\Authorization\AccessDecisionManager(new RewindableGenerator(function () {
    yield 0 => ($this->privates['debug.security.voter.security.access.authenticated_voter'] ?? $this->load('getDebug_Security_Voter_Security_Access_AuthenticatedVoterService.php'));
    yield 1 => ($this->privates['debug.security.voter.security.access.simple_role_voter'] ?? $this->load('getDebug_Security_Voter_Security_Access_SimpleRoleVoterService.php'));
}, 2), 'affirmative', false, true));
