<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7xVonyP' shared service.

return $this->privates['.service_locator.7xVonyP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'producer' => ['services', 'old_sound_rabbit_mq.send_email_producer', 'getOldSoundRabbitMq_SendEmailProducerService.php', true],
]);
