<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVkYxCQS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVkYxCQS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVkYxCQS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVkYxCQS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVkYxCQS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VkYxCQS',
    'container.build_id' => '60003d37',
    'container.build_time' => 1548690455,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVkYxCQS');
