<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTgdFFFT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTgdFFFT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTgdFFFT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTgdFFFT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTgdFFFT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TgdFFFT',
    'container.build_id' => '2c428734',
    'container.build_time' => 1548711197,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTgdFFFT');
